package(default_visibility=['PUBLIC'])
subinclude('//.build_defs/make')

make_maven_jar(name='junit', id='junit:junit:4.12', deps=[':hamcrest-core'])
make_maven_jar(name='hamcrest-core', id='org.hamcrest:hamcrest-core:1.3')
