// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: example_go/services/04_grpc/proto/book.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_go_services_04_grpc_proto_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_example_go_services_04_grpc_proto_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_example_go_services_04_grpc_proto_book_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_go_services_04_grpc_proto_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_example_go_services_04_grpc_proto_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_example_go_services_04_grpc_proto_book_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_example_go_services_04_grpc_proto_book_proto protoreflect.FileDescriptor

var file_example_go_services_04_grpc_proto_book_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x30, 0x34, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x32, 0x2d, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x76,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x05, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x67, 0x6f,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x30, 0x34, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_go_services_04_grpc_proto_book_proto_rawDescOnce sync.Once
	file_example_go_services_04_grpc_proto_book_proto_rawDescData = file_example_go_services_04_grpc_proto_book_proto_rawDesc
)

func file_example_go_services_04_grpc_proto_book_proto_rawDescGZIP() []byte {
	file_example_go_services_04_grpc_proto_book_proto_rawDescOnce.Do(func() {
		file_example_go_services_04_grpc_proto_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_go_services_04_grpc_proto_book_proto_rawDescData)
	})
	return file_example_go_services_04_grpc_proto_book_proto_rawDescData
}

var file_example_go_services_04_grpc_proto_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_go_services_04_grpc_proto_book_proto_goTypes = []interface{}{
	(*Empty)(nil), // 0: Empty
	(*Book)(nil),  // 1: Book
}
var file_example_go_services_04_grpc_proto_book_proto_depIdxs = []int32{
	0, // 0: BookSerivce.ListBooks:input_type -> Empty
	1, // 1: BookSerivce.ListBooks:output_type -> Book
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_go_services_04_grpc_proto_book_proto_init() }
func file_example_go_services_04_grpc_proto_book_proto_init() {
	if File_example_go_services_04_grpc_proto_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_go_services_04_grpc_proto_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_go_services_04_grpc_proto_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_go_services_04_grpc_proto_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_go_services_04_grpc_proto_book_proto_goTypes,
		DependencyIndexes: file_example_go_services_04_grpc_proto_book_proto_depIdxs,
		MessageInfos:      file_example_go_services_04_grpc_proto_book_proto_msgTypes,
	}.Build()
	File_example_go_services_04_grpc_proto_book_proto = out.File
	file_example_go_services_04_grpc_proto_book_proto_rawDesc = nil
	file_example_go_services_04_grpc_proto_book_proto_goTypes = nil
	file_example_go_services_04_grpc_proto_book_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookSerivceClient is the client API for BookSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookSerivceClient interface {
	ListBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (BookSerivce_ListBooksClient, error)
}

type bookSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookSerivceClient(cc grpc.ClientConnInterface) BookSerivceClient {
	return &bookSerivceClient{cc}
}

func (c *bookSerivceClient) ListBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (BookSerivce_ListBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BookSerivce_serviceDesc.Streams[0], "/BookSerivce/ListBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookSerivceListBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookSerivce_ListBooksClient interface {
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookSerivceListBooksClient struct {
	grpc.ClientStream
}

func (x *bookSerivceListBooksClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookSerivceServer is the server API for BookSerivce service.
type BookSerivceServer interface {
	ListBooks(*Empty, BookSerivce_ListBooksServer) error
}

// UnimplementedBookSerivceServer can be embedded to have forward compatible implementations.
type UnimplementedBookSerivceServer struct {
}

func (*UnimplementedBookSerivceServer) ListBooks(*Empty, BookSerivce_ListBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}

func RegisterBookSerivceServer(s *grpc.Server, srv BookSerivceServer) {
	s.RegisterService(&_BookSerivce_serviceDesc, srv)
}

func _BookSerivce_ListBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookSerivceServer).ListBooks(m, &bookSerivceListBooksServer{stream})
}

type BookSerivce_ListBooksServer interface {
	Send(*Book) error
	grpc.ServerStream
}

type bookSerivceListBooksServer struct {
	grpc.ServerStream
}

func (x *bookSerivceListBooksServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

var _BookSerivce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BookSerivce",
	HandlerType: (*BookSerivceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBooks",
			Handler:       _BookSerivce_ListBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example_go/services/04_grpc/proto/book.proto",
}
