// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_go/services/04-grpc/proto/book.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_653e4a91bb7e69c8, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_653e4a91bb7e69c8, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Book)(nil), "Book")
}

func init() {
	proto.RegisterFile("example_go/services/04-grpc/proto/book.proto", fileDescriptor_653e4a91bb7e69c8)
}

var fileDescriptor_653e4a91bb7e69c8 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0x4e, 0x4e, 0x29,
	0x8e, 0x4f, 0xcf, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x37, 0x30, 0xd1,
	0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xca, 0xcf, 0xcf, 0xd6,
	0x03, 0x33, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0xb4, 0xb8, 0x58, 0x9c,
	0xf2, 0xf3, 0xb3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x22, 0x60,
	0xb6, 0x91, 0x2e, 0x17, 0x37, 0x48, 0x6d, 0x70, 0x6a, 0x51, 0x66, 0x59, 0x72, 0xaa, 0x90, 0x1c,
	0x17, 0xa7, 0x4f, 0x66, 0x71, 0x09, 0x48, 0xa8, 0x58, 0x88, 0x4d, 0x0f, 0x6c, 0x9e, 0x14, 0xab,
	0x1e, 0x88, 0xaf, 0xc4, 0x60, 0xc0, 0xe8, 0xc4, 0x1e, 0xc5, 0x0a, 0xb6, 0x2c, 0x89, 0x0d, 0x4c,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x10, 0xd8, 0x65, 0x6b, 0xa0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookSerivceClient is the client API for BookSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookSerivceClient interface {
	ListBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (BookSerivce_ListBooksClient, error)
}

type bookSerivceClient struct {
	cc *grpc.ClientConn
}

func NewBookSerivceClient(cc *grpc.ClientConn) BookSerivceClient {
	return &bookSerivceClient{cc}
}

func (c *bookSerivceClient) ListBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (BookSerivce_ListBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BookSerivce_serviceDesc.Streams[0], "/BookSerivce/ListBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookSerivceListBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookSerivce_ListBooksClient interface {
	Recv() (*Book, error)
	grpc.ClientStream
}

type bookSerivceListBooksClient struct {
	grpc.ClientStream
}

func (x *bookSerivceListBooksClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookSerivceServer is the server API for BookSerivce service.
type BookSerivceServer interface {
	ListBooks(*Empty, BookSerivce_ListBooksServer) error
}

// UnimplementedBookSerivceServer can be embedded to have forward compatible implementations.
type UnimplementedBookSerivceServer struct {
}

func (*UnimplementedBookSerivceServer) ListBooks(req *Empty, srv BookSerivce_ListBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}

func RegisterBookSerivceServer(s *grpc.Server, srv BookSerivceServer) {
	s.RegisterService(&_BookSerivce_serviceDesc, srv)
}

func _BookSerivce_ListBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookSerivceServer).ListBooks(m, &bookSerivceListBooksServer{stream})
}

type BookSerivce_ListBooksServer interface {
	Send(*Book) error
	grpc.ServerStream
}

type bookSerivceListBooksServer struct {
	grpc.ServerStream
}

func (x *bookSerivceListBooksServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

var _BookSerivce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BookSerivce",
	HandlerType: (*BookSerivceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBooks",
			Handler:       _BookSerivce_ListBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example_go/services/04-grpc/proto/book.proto",
}
