package(default_visibility=['PUBLIC'])
subinclude('//.build_defs/make')

make_web_toolchain(
    name = 'default',
    srcs = ['default'],
    # scripts = {
    #     'build': './default/scripts/build.js'
    # }
)
