package(default_visibility = ['PUBLIC'])

filegroup(name = 'make', srcs = [
    '//.build_defs/make/make-docker',
    '//.build_defs/make/make-go',
    '//.build_defs/make/make-java',
    '//.build_defs/make/make-python',
    '//.build_defs/make/make-web',
    '//.build_defs/make/make-rust',
    '//.build_defs/make/make-dotnet',
])
